version: 2
jobs:
  build:
    working_directory: ~/elasticio-rest-node
    docker:
      - image: node:10
      - image: rabbitmq:3.7
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Installing Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Running Tests
          command: npm test
